language: ruby
bundler_args: --without development
before_install:
  - gem update bundler
rvm:
  - 2.0.0
  - 2.3.1
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - rbx-2
  - ruby-head
matrix:
  include:
    - rvm: jruby-18mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
